### ISSUE TITLE
Migrating provider to 3.0

### ISSUE THREAD

**Issue by cincuranet** [dotnet/efcore#18900]
Is there any "document" describing all the changes when migrating provider from 2.2 to 3.0/3.1? I found #15405, but that's more or less only list of `providers-beware` tag for 3.0. What I'm mostly interested it changes in query processing and model handling, because that's where most of compilation errors happens for me at the moment.

**Comment by ajcvickers** [comment]
@cincuranet Unfortunately no. The team will try to provide help wherever we can. Also @roji and @lauxjpn have done this for Npgsql and MySQL and so may be able to help.

**Comment by roji** [comment]
@cincuranet anything in particular you're blocking on? I'd be happy to provide any assistance etc.

**Comment by cincuranet** [comment]
At the moment I'm trying to make it build, at least. Fair to say I blindly updated the references to 3.1 in the name of to see what's what. :D I'm looking into EFCore sources and commits in Npgsql to speed things up. If you can give me some pointers, it would be appreciated (I'll keep working on that myself, so whatever comes first is a win 8-)).

* Where's `RelationalModelBuilderAnnotations`, `RelationalPropertyAnnotations` and similar types?
* Replacements for `RelationalCompositeMemberTranslator`, `RelationalCompositeMethodCallTranslator`, `DefaultQuerySqlGenerator`, etc.?
* `RelationalConventionSetBuilder` and related?

**Comment by ajcvickers** [comment]
@cincuranet On the first point, see https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#provider-specific-metadata-api-changes. The API surface was flattened out. /cc @AndriySvyryd

**Comment by lauxjpn** [comment]
@cincuranet As a general guideline, you can dive into our https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/822 PR, which contains most of the conversion work done for the MySQL provider for the upgrade from 2.2.6 to 3.0.0, and consists of 79 individual commits with each of them containing a short description of what has been done.
It will also provide a general overview of what files were removed and added.

**Comment by cincuranet** [comment]
@lauxjpn That's in general what I do. But sometimes the code does not explain the reasoning behind and it's difficult to make a right decision if you don't know all the places that fit together especially as the code does not compile yet (at the moment trying to understand `ApplyTypeMapping`).

**Comment by lauxjpn** [comment]
@cincuranet I had similar problems when starting with the migration. I just mirrored what Npgsql or Sqlite did and left bookmarks behind when I was unsure about decisions I made on the spot, to which I came back to after I got everything to compile and thus the tests to run again.
