### ISSUE TITLE
Azure DevOps build fails after updating to .NET/EF Core 6, ModelShapShot with long (64bit int) id fails

### ISSUE THREAD

**Issue by coffeymatt** [dotnet/efcore#27501]
I'm getting a very strange issue with Azure DevOps after updating my ASP.NET from 5 to 6, which uses entity framework and SQL server. My build pipeline is set to use .NET 6.0.x, and the windows-2022 agent from the pool. My EF Core dlls are 6.0.2.

The project builds fine locally, but with the .NET build task on Azure DevOps, I get compilation errors. It complains about the 'AppDbContextModelSnapshot.cs' file. It seems going from .NET5 to 6 has added these automatically generated lines to this file

Going from this in .NET/EF 5:

```
b.Property<long>("Id")
     .ValueGeneratedOnAdd()
     .HasColumnType("bigint")
     .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
```

To this in .NET/EF 6:

```
b.Property<long>("Id")
   .ValueGeneratedOnAdd()
   .HasColumnType("bigint");

SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);
```

Note: the type for the PK of the entity is a 'long'.

This builds runs locally, migrates fine locally, but on deployment to Azure DevOps for a build, produces these exceptions:

Data\Application\Migrations\AppDbContextModelSnapshot.cs(24,78): Error CS1503: Argument 2: cannot convert from 'long' to 'int'

I can manually edit the generated code to remove the arguments e.g. :

`SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);`

But, to build on DevOps I have to do this hacky work around every time I add a new migration. Why is it complaining on (Azure DevOps build only)? I can't see anything wrong with the code locally, and cannot see where this conversion is coming from.

### Include provider and version information

EF Core version: 6.0.2
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 6.0.x
Operating system: windows-2022 agent from Azure pipelines agent pool
IDE: Visual Studio 2022 17.0.6

**Comment by roji** [comment]
@coffeymatt EF Core 6.0.2 does have an [overload of UseIdentityColumn](https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Extensions/SqlServerPropertyBuilderExtensions.cs#L152) which accepts a long seed - are you sure you're not somehow using an older version of EF Core when deploying to Azure DevOps?

If not, I'd try to concentrate on the difference between your local build (which works) and the failure on Azure DevOps. If you can get a project sample which shows the build failing, we'd be able to investigate further.

**Comment by ajcvickers** [comment]
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by coffeymatt** [comment]
@ajcvickers Can you re-open please, I just hadn't had time to respond yet.

This is still very much an issue. I'm certain I'm not using an older version of EF core on Azure devops, my build restores the same package versions from nuget. It's the same version of .NET Core 6.0.201, I have a 'Use .NET Core' step to define the version.

Project wise, you simply need a project with a single entity where the id property e.g.

```
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
```

Generate a migration, then try and get that to build on Azure DevOps

![image](https://user-images.githubusercontent.com/32092194/157667596-68308c62-6f68-4742-a00a-62858c9b73a8.png)

**Comment by roji** [comment]
@coffeymatt we still need some sort of repro to investigate this. However, since you're saying the project builds fine for you locally and only fails in AzDo, that really points to some sort of configuration issue in your AzDo setup - as you can see, EF Core itself does have the long identity overload (since it builds locally).

Note that there's no EF Core with version 6.0.201 - that's a .NET SDK version.  The latest version of EF Core is currently 6.0.3.

**Comment by coffeymatt** [comment]
@roji Thanks Roji, I've been absolutely baffled by this seen as locally and on the build, it's set up to load 6.0.3 of EF via the package config (which is what I could see in package manager console as that version). However, I've just looked at the csproj file and for whatever reason (probably something some one has merged) it's got the 'EntityFramworkCore.SqlServer' referenced twice with two different versions. Don't know why DevOps behaved differently to local, but it must have picked the other version.

Thanks for prompting me to look in the right place.
