### ISSUE TITLE
Compiled model - problem with large models

### ISSUE THREAD

**Issue by ZvonimirMatic** [dotnet/efcore#32591]
I'm using a compiled model because I'm working with a database with around 1200 tables. Everything worked fine with EF Core 7.

I'm trying to upgrade to EF Core 8, but when I try to generate a compiled model, I run into a problem. The compiled model is generated correctly, but when I try to build the project, I get an error: `error CS0204: Only 65534 locals, including those generated by the compiler, are allowed`. As to my understanding, in the built model's `CreateRelationalModel` method, I have more than 65534 local variables.

Is there a way to avoid generating the relational model or some other workaround other than deleting the method manually? This could be problematic, since compiled model will be used in projects with large models, and a lot of them might have large amounts of local variables.

If I'm not mistaken, the change was introduced in the PR #30494.

EF Core version: 8.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Windows 11
IDE: Visual Studio 2022 17.8.3

**Comment by ajcvickers** [comment]
Duplicate of #31370
