### ISSUE TITLE
SQL Server - ModelBuilder.Query<T>().ToTable Missing

### ISSUE THREAD

**Issue by twurm** [dotnet/efcore#11694]
### Describe what is not working as expected.

When upgrading from EF Core 2.1 Preview 1 to Preview 2 we are seeing the following build errors:
error CS1929: 'QueryTypeBuilder<BlogPostsCount>' does not contain a definition for 'ToTable' and the best extension method overload 'RelationalEntityTypeBuilderExtensions.ToTable(EntityTypeBuilder, string)' requires a receiver of type 'EntityTypeBuilder'

### Steps to reproduce
[Example Project](https://github.com/aspnet/EntityFrameworkCore/tree/dev/samples/QueryTypes)
[Microsoft Docs: Query Types](https://docs.microsoft.com/en-us/ef/core/modeling/query-types)

Steps:
Try to build the above project.

The following code will generate the error when using 2.1.0-preview2-final but not when using 2.1.0-preview1-final
```c#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    // Worked in 2.1.0-preview1-final 
    modelBuilder
        .Query<BlogPostsCount>().ToTable("View_BlogPostCounts")
        .Property(v => v.BlogName).HasColumnName("Name");
}
```

### Further technical details
EF Core version: 2.1.0-preview2-final 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 (Insider Slow Ring)
IDE: VS 2017 15.7.0 Preview 3
