### ISSUE TITLE
Could not load type 'Microsoft.Data.SQLite.SQLiteDataReader'

### ISSUE THREAD

**Issue by rburkitt** [dotnet/efcore#1359]
Unable to connect to sqlite db on Mono/OSx:

An unhandled exception occurred while processing the request.

TypeLoadException: Could not load type 'Microsoft.Data.SQLite.SQLiteDataReader' from assembly 'Microsoft.Data.SQLite, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by bricelam** [comment]
What does your project.json (or packages.config) look like?

**Comment by rburkitt** [comment]
I'll try and send this to you later today, but I think my problem is the
version of Mono.

I had followed the directions on the website to set up the K environment
and assumed it installed the correct version of Mono, but it looks like
3.1.0 was installed.

I'm going to try and download and compile version 3.8.0 and see if I can
get the system to use that instead.

It's amazing how much worked on mono 3.1.0, the db was created and seemed
to connect, but migrations and reading data failed.

**Comment by rburkitt** [comment]
unable to get any version higher than mono 3.1.0 to install on my system,
and I'm guessing that is the reason for ef migrations not working

**Comment by bricelam** [comment]
It may not actually work at all. We depend on the .NET 4.5.1 System.Data.Common APIs, but Mono is still only at .NET 4.5. We're working with them to get it updated, but it looks like it still hasn't happened.

**Comment by rburkitt** [comment]
Oh shoot, I had hoped it worked, I guess I'll have to wait for an official
build from mono.

Want me to close out the issue I filed?

**Comment by bricelam** [comment]
If you really want to start hacking on Mono today, you could clone the repositories, update them to target net45 (instead of net451), and fix any compilation errors.

**Comment by rburkitt** [comment]
Everything but EntityFramework7 seems to work, do you think I would need to
clone all of the repositories or just EE7?

**Comment by bricelam** [comment]
Probably EF7 and Microsoft.Data.SQLite
