### ISSUE TITLE
Fix build on Linux

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/efcore#5505]
Changes in #5494 added references in System.Data.Common.DbParameter API that is technically in the .NET 4.5.1 API surface, but missing from Mono reference assemblies. 

> fail: /home/travis/.dotnet/dotnet compile-csc @/home/travis/build/aspnet/EntityFramework/src/Microsoft.EntityFrameworkCore.Relational/obj/Debug/net451/dotnet-compile.rsp returned Exit Code 1
> fail: /home/travis/build/aspnet/EntityFramework/src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalLoggerExtensions.cs(51,35): error CS1061: 'DbParameter' does not contain a definition for 'Precision' and no extension method 'Precision' accepting a first argument of type 'DbParameter' could be found (are you missing a using directive or an assembly reference?)
> fail: /home/travis/build/aspnet/EntityFramework/src/Microsoft.EntityFrameworkCore.Relational/Extensions/RelationalLoggerExtensions.cs(52,35): error CS1061: 'DbParameter' does not contain a definition for 'Scale' and no extension method 'Scale' accepting a first argument of type 'DbParameter' could be found (are you missing a using directive or an assembly reference?)

See mono bug by @bricelam and @divega: https://bugzilla.xamarin.com/show_bug.cgi?id=29167

Even though we don't run tests against Mono anymore, dotnet build on Linux/OSX still uses Mono reference assemblies to compile.

Solutions:
1. Update Mono ref assemblies to pre-release versions that have the API surface. 
2. Change our code.
3. Set DOTNET_REFERENCE_ASSEMBLIES_PATH to a folder that contains proper .NET 4.5.1 reference assemblies. (see [DotNetReferenceAssembliesPathResolver](https://github.com/dotnet/cli/blob/f8631fa4b731d4c903dbe8b0b5e5332eee40ecae/src/Microsoft.Extensions.DependencyModel/Resolution/DotNetReferenceAssembliesPathResolver.cs))
4. Alter build script to not build for desktop .NET on Linux/OSX.

**Comment by natemcmaster** [comment]
cc @pranavkm @Eilon what do you think about solution 4?

**Comment by divega** [comment]
FWIW, solution 3 looks like a good choice to me, assuming we can make it work.

**Comment by pranavkm** [comment]
cc @davidfowl - we have a similar issue building some of the incoming changes with Logging (https://github.com/aspnet/Logging/pull/434). Do you have ideas on how we'd get the correct reference assemblies on Travis?

**Comment by natemcmaster** [comment]
I'm testing a travis build with Mono beta (currently 4.4.0 RC1). https://github.com/aspnet/EntityFramework/commit/db4cd2db22b94dfe61e78ce68c496895368462db and https://travis-ci.org/aspnet/EntityFramework/builds/132707297. We've had issues with Sake + newer versions of Mono. Hopefully those are fixed now.

**Comment by Eilon** [comment]
(3) would be nice, assuming we can do it. Option (4) is potentially reasonable as a short-term solution, but is not a valid long-term solution. So if we do (4) to unblock things, log a new bug to revert (4) and find a proper long-term solution.

**Comment by divega** [comment]
BTW solution 3 is a .NET 4.5.1 multi-targetting pack for Linux and OSX 😉

**Comment by natemcmaster** [comment]
Fixed with 24a9526caa83bd58d8c4ba84ec663f256f53ce07. We may need to update other CI agents.
