### ISSUE TITLE
Missing SeedData Method

### ISSUE THREAD

**Issue by hafeefshaik** [dotnet/efcore#11629]
Getting below error after updating nugget packages form 2.0.1-Preview1-Final to 2.0.1-Preview2-Final

'EntityTypeBuilder' does not contain a definition for 'SeedData' and no extension method 'SeedData' accepting a first argument of type 'EntityTypeBuilder' could be found (are you missing a using directive or an assembly reference?)

**Comment by ErikEJ** [comment]
It has been renamed to HasData

**Comment by hafeefshaik** [comment]
In that case, How can I deal with existing migrations, do I need to rename it or remove form the migrations.

**Comment by ErikEJ** [comment]
Rename... It is beta software..

**Comment by hafeefshaik** [comment]
Thanks @ErikEJ

**Comment by koshishrijal** [comment]
error CS1061: 'EntityTypeBuilder<Student>' does not contain a definition for 'HasData' and no extension method 'HasData' accepting a first argument of type 'EntityTypeBuilder<Student>' could be found (are you missing a using directive or an assembly reference?)
1>Done building project "CollegeRest.csproj" -- FAILED.

**Comment by ajcvickers** [comment]
@koshishrijal If you feel this is an EF bug, then please file a new issue will full details.
