### ISSUE TITLE
Fix disambiguity in System.Linq extension methods when using EF Core 3.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/efcore#20419]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/954255/fix-disambiguity-in-systemlinq-extension-methods-w.html)._

---
<p>Hello,</p><p>My app targets <strong>.NET Framework 4.7.2</strong> (but in newest <strong>4.8</strong> the problem persists) and references <strong>.NET Standard 2.0</strong>  library which provides database context using<strong> </strong><strong>EF Core 3.1</strong>.</p> <p>It is normal practice to combine EF with LINQ, therefore I add these two usings:</p><pre>using System.Linq;</pre> <pre>using Microsoft.EntityFrameworkCore;</pre> <p>With this setting plain simple where expression fails:<br> <code>var test = context. Accounts.Where(i =&gt; i.Active == true). ToList();</code></p> <p>generates error</p><blockquote><p>error CS0121: The call is ambiguous between the following methods or  properties: 'System.Linq.Queryable.Where(System.Linq.IQueryable,  System.Linq.Expressions.Expression&lt;System.Func&lt;TSource,  bool&gt;&gt;)' and  'System.Linq.AsyncEnumerable.Where(System.Collections.Generic.IAsyncEnumerable,  System.Func&lt;TSource, bool&gt;)'</p></blockquote><p></p><p>On the other hand it compiles just fine in my another app targeting <strong>ASP .NET Core 3.1</strong>  which references the same library, so the issue arises in my case when  <strong>combining .NET Framework with EF Core 3.1</strong>. <code></code></p><p> 
</p><p>According to EF Core devs, this is not their fault, but rather  <i>&quot;design mistake on IX-Async part to add their methods inside System.Linq namespace</i>&quot;.</p> <p>The issue mainly exists when using async, but notice that in this case I don't use async functionality at all, just having these two usings (which is common use case) plain simple Where() expression is not possible anymore.</p> <p> 
</p><p>Yes, EF Core team created a hot fix to cast <strong>DbSet&lt;&gt; </strong>into <strong>IQueryable&lt;&gt; </strong>using <code>AsQueryable()</code>:</p><p><code>var test = context. Accounts.AsQueryable(). Where(i =&gt; i.Active == true). ToList();</code></p> <p> 
</p><p>But.. it feels a bit ugly when you worked without it for many years, any chance of it being fixed somehow?</p> <p>Cheers</p>

---
#### Visual Studio Feedback System on 3/18/2020, 04:53 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 3/18/2020, 06:15 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Visual Studio Feedback System on 3/23/2020, 11:51 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
Duplicate of #18124
